{
 "title": "Polkadot and parachains full monitoring",
 "description": "All in one monitoring for Substrate based Relay chain, Parachains and backups",
 "tags": [ "prod" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "chain", "query": { "query": "label_values(chain)" } },
   { "name": "job", "label": "job", "query": "dynamic" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(substrate_block_height{chain=\"$chain\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Block Height (best)",
   "type": "stat",
   "description": "What your node sees as the highest block (NOT finalized)",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\", chain=\"$chain\", pod=\"$pod\"}",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "Block Height (finalized)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"finalized\", chain=\"$chain\", pod=\"$pod\"}",
     "legendFormat": "Height(finalized)"
    }
   ]
  },
  {
   "title": "Active validator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "polkadot_node_is_active_validator{job=\"$job\", chain=\"$chain\", pod=\"$pod\"}",
     "legendFormat": "{{chain}} validator"
    },
    {
     "expr": "polkadot_node_is_parachain_validator{job=\"$job\", chain=\"$chain\", pod=\"$pod\"}",
     "legendFormat": "{{chain}} para validator"
    }
   ]
  },
  {
   "title": "Block Total Tx",
   "type": "stat",
   "description": "Total transactions in best block",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_proposer_number_of_transactions{chain=\"$chain\", job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "Height(best)"
    }
   ]
  },
  {
   "title": "State Cashe (bytes)",
   "type": "stat",
   "description": "What your node sees as the highest finalized block ( less than or equal to best)",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{chain=\"$chain\", job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "Size (bytes)"
    }
   ]
  },
  {
   "title": "libp2p peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{job=\"dynamic\",chain='$chain', pod=\"$pod\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "LibP2P peers",
   "type": "timeseries",
   "description": "Number of connected peers",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{chain=\"$chain\", job=\"$job\", pod=\"$pod\"}",
     "legendFormat": "Number of network gossip peers"
    }
   ]
  },
  {
   "title": "Block rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "increase(substrate_block_height{status=\"best\",job=\"$job\",chain='$chain', pod=\"$pod\"}[5m])/5",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Transaction queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{job=\"$job\",chain=~'$chain', pod=\"$pod\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Proposer Block Construction Time",
   "type": "timeseries",
   "description": "histogram 90th quantiles for time to construct a block (seconds) More info: https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(substrate_proposer_block_constructed_bucket{job=\"$job\", pod=\"$pod\", chain=\"$chain\"}[5m])))",
     "legendFormat": "90th quantile for block construction time (s)"
    }
   ]
  },
  {
   "title": "Chain",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "substrate_build_info{job=\"$job\",chain=~'$chain', pod=\"$pod\"}"
    },
    {
     "expr": "substrate_block_height{job=\"$job\",chain=~'$chain',status=\"best\", pod=\"$pod\"}"
    },
    {
     "expr": "substrate_block_height{job=\"$job\",chain=~'$chain',status=\"finalized\", pod=\"$pod\"}"
    },
    {
     "expr": "substrate_sub_libp2p_peers_count{job=\"$job\",chain=~'$chain', pod=\"$pod\"}"
    },
    {
     "expr": "avg by (chain)(rate(substrate_block_height{job=\"$job\",chain=~'$chain',status=\"best\", pod=\"$pod\"}[7d])*60)"
    },
    {
     "expr": "avg by (chain)(rate(substrate_block_height{job=\"$job\",chain=~'$chain',status=\"best\", pod=\"$pod\"}[1d])*60)"
    },
    {
     "expr": "avg by (chain)(rate(substrate_block_height{job=\"$job\",chain=~'$chain',status=\"best\", pod=\"$pod\"}[1h])*60)"
    },
    {
     "expr": "avg by (chain)(rate(substrate_block_height{job=\"$job\",chain=~'$chain',status=\"best\", pod=\"$pod\"}[5m])*60)"
    },
    {
     "expr": "up{job=\"$job\",chain=~'$chain',instance=~\".*9615\", pod=\"$pod\"}"
    }
   ]
  }
 ]
}