/*
 * Copyright (C) Zeeve Inc.
 * This file is part of Larch.
 * Larch is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * Larch is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * You should have received a copy of the GNU General Public License
 * along with Larch.  If not, see <http://www.gnu.org/licenses/>.
 */

export const NETWORK_PROVIDER = "podman"
export const DIRECTORY_NAME = "/home/antar/.larch/zomb-net"
export const FILE_NAME = "0001-small-network.json"
export const NETWORK_NAME = "TestingNetwork"
export const TEST_NETWORK_NAME = "MyTestNetwork"
export const CONFIG_FILE = "ewogICJyZWxheWNoYWluIjogewogICAgImRlZmF1bHRfaW1hZ2UiOiAiZG9ja2VyLmlvL3Bhcml0eS9wb2xrYWRvdDpsYXRlc3QiLAogICAgImRlZmF1bHRfY29tbWFuZCI6ICJwb2xrYWRvdCIsCiAgICAiZGVmYXVsdF9hcmdzIjogWwogICAgICAiLWxwYXJhY2hhaW49ZGVidWciCiAgICBdLAogICAgImNoYWluIjogInJvY29jby1sb2NhbCIsCiAgICAibm9kZXMiOiBbCiAgICAgIHsKICAgICAgICAibmFtZSI6ICJhbGljZSIsCiAgICAgICAgInZhbGlkYXRvciI6IHRydWUKICAgICAgfSwKICAgICAgewogICAgICAgICJuYW1lIjogImJvYiIsCiAgICAgICAgInZhbGlkYXRvciI6IHRydWUKICAgICAgfQogICAgXQogIH0sCiAgInBhcmFjaGFpbnMiOiBbCiAgICB7CiAgICAgICJpZCI6IDEwMCwKICAgICAgImNvbGxhdG9yIjogewogICAgICAgICJuYW1lIjogImNvbGxhdG9yMDEiLAogICAgICAgICJpbWFnZSI6ICJkb2NrZXIuaW8vcGFyaXR5L3BvbGthZG90LXBhcmFjaGFpbjpsYXRlc3QiLAogICAgICAgICJjb21tYW5kIjogInBvbGthZG90LXBhcmFjaGFpbiIsCiAgICAgICAgImFyZ3MiOiBbCiAgICAgICAgICAiLWxwYXJhY2hhaW49ZGVidWciCiAgICAgICAgXQogICAgICB9CiAgICB9CiAgXSwKICAiaHJtcF9jaGFubmVscyI6IFtdCn0K"

export const TEST_FILE_NAME = "0001-small-network.zndsl"
export const TEST_FILE_CONTENT = "RGVzY3JpcHRpb246IFNtYWxsIE5ldHdvcmsgdGVzdApOZXR3b3JrOiAuL1Rlc3RpbmdOZXR3b3JrLWNvbmZpZy5qc29uCkNyZWRzOiBjb25maWcKCiMgVHJhY2luZwojIGFsaWNlOiB0cmFjZSB3aXRoIHRyYWNlSUQgOTRjMTUwMWE3OGEwZDgzYzQ5OGNjOTJkZWVjMjY0ZDkgY29udGFpbnMgWyJhbnN3ZXItY2h1bmstcmVxdWVzdCIsICJhbnN3ZXItY2h1bmstcmVxdWVzdCJdCgojIG1ldHJpY3MKYWxpY2U6IHJlcG9ydHMgbm9kZV9yb2xlcyBpcyA0CmFsaWNlOiByZXBvcnRzIHN1Yl9saWJwMnBfaXNfbWFqb3Jfc3luY2luZyBpcyAwCgojIGhpc3RvZ3JhbQphbGljZTogcmVwb3J0cyBoaXN0b2dyYW0gcG9sa2Fkb3RfcHZmX2V4ZWN1dGlvbl90aW1lIGhhcyBhdCBsZWFzdCAyIHNhbXBsZXMgaW4gYnVja2V0cyBbIjAuMSIsICIwLjI1IiwgIjAuNSIsICIrSW5mIl0gd2l0aGluIDEwMCBzZWNvbmRzCgojIGxvZ3MKYm9iOiBsb2cgbGluZSBtYXRjaGVzIGdsb2IgIipydGVkICMxKiIgd2l0aGluIDEwIHNlY29uZHMKYm9iOiBsb2cgbGluZSBtYXRjaGVzICJJbXBvcnRlZCAjWzAtOV0rIiB3aXRoaW4gMTAgc2Vjb25kcwoKIyBzeXN0ZW0gZXZlbnRzCmJvYjogc3lzdGVtIGV2ZW50IGNvbnRhaW5zICJBIGNhbmRpZGF0ZSB3YXMgaW5jbHVkZWQiIHdpdGhpbiAyMCBzZWNvbmRzCmFsaWNlOiBzeXN0ZW0gZXZlbnQgbWF0Y2hlcyBnbG9iICIqd2FzIGJhY2tlZCoiIHdpdGhpbiAxMCBzZWNvbmRzCgojcGFyYWNoYWluIHRlc3RzCmFsaWNlOiBwYXJhY2hhaW4gMTAwIGlzIHJlZ2lzdGVyZWQgd2l0aGluIDIyNSBzZWNvbmRzCmFsaWNlOiBwYXJhY2hhaW4gMTAwIGJsb2NrIGhlaWdodCBpcyBhdCBsZWFzdCAxMCB3aXRoaW4gMjAwIHNlY29uZHMK"